language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1
  - nightly
codecov: true
jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "SCOPF Solver Scripts"
      julia: 1.0
      os: linux
      script:
        - julia --project -e 'using Pkg; Pkg.instantiate(); Pkg.add("Ipopt"); Pkg.add("Cbc")'
        - julia --project src/scripts/test-MyJulia.jl
      after_success: skip
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs/ docs/make.jl
      after_success: skip
